/* lang-data.js — Translation strings only. Loaded in <head> so they are
   available before the page renders. Keep this file pure data — no DOM access. */

var TRANSLATIONS = {
  en: {
    nav_home:"Home", nav_services:"Services", nav_packages:"Packages",
    nav_gallery:"Gallery", nav_about:"About Us", nav_contact:"Contact Us",
    home_title:"Welcome to Loving Homes Dog Hotel",
    home_sub1:"We are committed to giving your dog the best care possible.",
    home_sub2:"Join us for a healthier, happier life for your beloved companion!",
    video_fallback:"Your browser does not support video playback.",
    services_heading:"Our Services & Facilities",
    services_intro:"At Loving Homes we provide a wide range of services to ensure your dog has a comfortable and enjoyable stay.",
    s1_title:"Luxury Boarding Rooms", s1_text:"Private rooms with underfloor heating and cooling, flat-screen TV, and fresh bedding changed daily.",
    s2_title:"Grooming Parlour & Spa", s2_text:"Full grooming services: baths, breed-specific haircuts, nail clipping, ear cleaning, and spa treatments.",
    s3_title:"Secure Outdoor Paddocks", s3_text:"Spacious, fully-secured outdoor paddocks for free play and fresh air every day.",
    s4_title:"Woodland Walks", s4_text:"Scenic guided walks through natural woodland areas — great for exercise and mental stimulation.",
    s5_title:"Indoor Play Barn", s5_text:"A large indoor play area perfect for all weather conditions and interactive group play.",
    s6_title:"Chauffeur Service", s6_text:"Stress-free door-to-door collection and return service across Hong Kong.",
    s7_title:"24/7 Veterinary Care", s7_text:"Our on-call veterinary team is available around the clock for complete peace of mind.",
    s8_title:"Pet Watch", s8_text:"Continuous monitoring and daily health checks for every guest staying with us.",
    s9_title:"Private Grass Area", s9_text:"A dedicated private grass space for your dog to relax, explore, and enjoy outdoor time away from the group.",
    packages_heading:"Our Packages",
    packages_intro:"Choose the package that best suits your dog's needs — from a single day visit to an extended luxury stay.",
    pkg1_name:"Premium Package", pkg1_f1:"Four walks/activities per day", pkg1_f2:"Private grass area", pkg1_f3:"Daily photo & video updates", pkg1_f4:"Treats as agreed with owner", pkg1_f5:"Luxury room with underfloor heating/cooling & TV", pkg1_f6:"Door-to-door chauffeur service", pkg1_f7:"24/7 veterinary care", pkg1_f8:"Continuous pet monitoring", pkg1_f9:"Grooming parlour & spa access", pkg1_f10:"Secure outdoor paddocks",
    pkg2_name:"Classic Package", pkg2_f1:"Three walks/activities per day", pkg2_f2:"Indoor play barn", pkg2_f3:"Zen zone relaxation", pkg2_f4:"Grooming session", pkg2_f5:"Luxury room with underfloor heating/cooling & TV", pkg2_f6:"Door-to-door chauffeur service", pkg2_f7:"24/7 veterinary care", pkg2_f8:"Continuous pet monitoring", pkg2_f9:"Secure outdoor paddocks",
    pkg3_name:"Day Package", pkg3_f1:"Two walks per day", pkg3_f2:"External play area", pkg3_f3:"Agility track", pkg3_f4:"Sand digging pit", pkg3_f5:"Door-to-door chauffeur service", pkg3_f6:"24/7 veterinary care", pkg3_f7:"Continuous pet monitoring", pkg3_f8:"Secure outdoor paddocks",
    pkg_custom_title:"Custom Packages",
    pkg_custom_text:"Custom packages are available for longer stays or for dogs with additional requirements. Please contact us to arrange a custom package.",
    gallery_heading:"Photo Gallery",
    gallery_intro:"Take a look at our happy guests enjoying their stay at Loving Homes.",
    about_heading:"About Loving Homes",
    about_p1:"Loving Homes is a premium dog hotel based in Hong Kong. We are dedicated to providing a safe, comfortable, and enjoyable environment for your beloved pet.",
    about_p2:"Our team of experienced and passionate animal lovers offers a wide range of services, from luxury boarding rooms and expert grooming to woodland walks and 24-hour veterinary care.",
    about_p3:"We believe every dog deserves to feel at home — even when their owners are away. That is why we treat every guest with the same love and attention we would give our own pets.",
    about_p4:"Founded by a group of dog enthusiasts in Hong Kong, Loving Homes has grown to become one of the city's most trusted dog hotels.",
    about_mission_heading:"Our Mission",
    about_mission_text:"To provide the finest care for every dog that walks through our doors — treating them like family, not guests.",
    about_vision_heading:"Our Vision",
    about_vision_text:"To be Hong Kong's leading premium dog hotel, setting the gold standard for pet hospitality, safety, and wellbeing.",
    about_values_heading:"Our Values",
    about_v1_title:"Safety First", about_v1_text:"Every dog is monitored 24/7 by trained staff and on-call veterinarians.",
    about_v2_title:"Genuine Care", about_v2_text:"We treat every guest with the same love we give our own pets.",
    about_v3_title:"Excellence", about_v3_text:"From luxury rooms to grooming, we maintain the highest standards in everything we do.",
    about_v4_title:"Transparency", about_v4_text:"Daily photo and video updates keep you connected with your dog at all times.",
    about_team_heading:"Our Team",
    about_team_text:"Our dedicated team includes certified veterinarians, experienced groomers, trained dog handlers, and passionate animal lovers — all committed to making your dog's stay extraordinary.",
    about_blog_heading:"About This Website",
    about_blog_p1:"This website was created to help dog owners in Hong Kong find reliable, high-quality care for their pets.",
    about_blog_p2:"You will find detailed information about our services, packages, and facilities, along with tips and advice on dog care.",
    about_blog_p3:"Whether you are planning a holiday or simply need daytime care for your dog, Loving Homes is here to help.",
    contact_heading:"Contact Us",
    contact_intro:"We are here to help. If you have any questions or would like to make a booking, please get in touch:",
    location_heading:"Our Location",
    location_text:"Find us at the heart of Hong Kong. We're conveniently located and easy to reach.",
    lbl_fname:"First Name:", lbl_lname:"Last Name:", lbl_email:"Email Address:",
    lbl_message:"Message:",
    btn_send:"Send",
    err_required:"This field is required.",
    success_msg:"✔ Thank you! Your message has been received. We will get back to you shortly.",
    status_fill:"Please fill in all required fields.",
    status_sending:"Sending…",
    footer_text:"© 2026 Loving Homes Dog Hotel - All rights reserved - Hong Kong, Made by Lujain Omar Khlifat",
  },
  ar: {
    nav_home:"الرئيسية", nav_services:"الخدمات", nav_packages:"الباقات",
    nav_gallery:"المعرض", nav_about:"من نحن", nav_contact:"اتصل بنا",
    home_title:"مرحبًا بك في فندق الكلاب لوفينج هومز",
    home_sub1:"نحن ملتزمون بمنح كلبك أفضل رعاية ممكنة.",
    home_sub2:"انضم إلينا لحياة أكثر صحة وسعادة لرفيقك المحبوب!",
    video_fallback:"متصفحك لا يدعم تشغيل الفيديو.",
    services_heading:"خدماتنا ومرافقنا",
    services_intro:"في لوفينج هومز نقدم مجموعة واسعة من الخدمات لضمان إقامة مريحة وممتعة لكلبك.",
    s1_title:"غرف إقامة فاخرة", s1_text:"غرف خاصة بتدفئة وتبريد أرضي وتلفزيون شاشة مسطحة وفراش نظيف يُغير يومياً.",
    s2_title:"صالون التزيين والسبا", s2_text:"خدمات تزيين متكاملة: استحمام، قص شعر، قص أظافر، تنظيف أذنين، وجلسات سبا.",
    s3_title:"مراعٍ خارجية آمنة", s3_text:"مراعٍ خارجية واسعة ومؤمنة بالكامل للعب الحر والهواء الطلق يومياً.",
    s4_title:"التنزه في الغابة", s4_text:"نزهات مرشدة في مناطق طبيعية خلابة — رائعة للتمرين والتحفيز الذهني.",
    s5_title:"صالة الألعاب الداخلية", s5_text:"منطقة لعب داخلية كبيرة مثالية لجميع الأحوال الجوية واللعب الجماعي.",
    s6_title:"خدمة السيارة", s6_text:"خدمة استلام وتوصيل من الباب للباب بدون توتر في جميع أنحاء هونغ كونغ.",
    s7_title:"رعاية بيطرية 24/7", s7_text:"فريقنا البيطري متاح على مدار الساعة لضمان راحة البال الكاملة.",
    s8_title:"مراقبة الحيوانات الأليفة", s8_text:"مراقبة مستمرة وفحوصات صحية يومية لكل ضيف لدينا.",
    s9_title:"مساحة عشب خاصة", s9_text:"مساحة عشب خاصة مخصصة لكلبك للاسترخاء والاستكشاف والاستمتاع بوقت في الهواء الطلق بعيداً عن المجموعة.",
    packages_heading:"باقاتنا",
    packages_intro:"اختر الباقة المناسبة لكلبك — من زيارة يوم واحد إلى إقامة فاخرة ممتدة.",
    pkg1_name:"الباقة المميزة", pkg1_f1:"أربع نزهات/أنشطة يومياً", pkg1_f2:"مساحة عشب خاصة", pkg1_f3:"تحديثات صور وفيديو يومية", pkg1_f4:"مكافآت متفق عليها مع المالك", pkg1_f5:"غرفة فاخرة بتدفئة/تبريد أرضي وتلفزيون", pkg1_f6:"خدمة توصيل من الباب للباب", pkg1_f7:"رعاية بيطرية 24/7", pkg1_f8:"مراقبة مستمرة للحيوانات الأليفة", pkg1_f9:"صالون التزيين والسبا", pkg1_f10:"مراعٍ خارجية آمنة",
    pkg2_name:"الباقة الكلاسيكية", pkg2_f1:"ثلاث نزهات/أنشطة يومياً", pkg2_f2:"صالة الألعاب الداخلية", pkg2_f3:"استرخاء في المنطقة الهادئة", pkg2_f4:"جلسة تزيين", pkg2_f5:"غرفة فاخرة بتدفئة/تبريد أرضي وتلفزيون", pkg2_f6:"خدمة توصيل من الباب للباب", pkg2_f7:"رعاية بيطرية 24/7", pkg2_f8:"مراقبة مستمرة للحيوانات الأليفة", pkg2_f9:"مراعٍ خارجية آمنة",
    pkg3_name:"الباقة اليومية", pkg3_f1:"نزهتان يومياً", pkg3_f2:"منطقة اللعب الخارجية", pkg3_f3:"مسار الرشاقة", pkg3_f4:"حفرة الرمل", pkg3_f5:"خدمة توصيل من الباب للباب", pkg3_f6:"رعاية بيطرية 24/7", pkg3_f7:"مراقبة مستمرة للحيوانات الأليفة", pkg3_f8:"مراعٍ خارجية آمنة",
    pkg_custom_title:"الباقات المخصصة",
    pkg_custom_text:"تتوفر باقات مخصصة للإقامات الطويلة أو للكلاب ذات المتطلبات الخاصة. تواصل معنا لترتيب باقة مخصصة.",
    gallery_heading:"معرض الصور",
    gallery_intro:"تعرف على ضيوفنا السعداء وهم يستمتعون بإقامتهم في لوفينج هومز.",
    about_heading:"عن لوفينج هومز",
    about_p1:"لوفينج هومز فندق كلاب فاخر يقع في هونغ كونغ. نحن ملتزمون بتوفير بيئة آمنة ومريحة وممتعة لحيوانك الأليف.",
    about_p2:"يقدم فريقنا من عشاق الحيوانات ذوي الخبرة مجموعة واسعة من الخدمات، من غرف الإقامة الفاخرة والتزيين الاحترافي إلى المشي في الغابة والرعاية البيطرية على مدار الساعة.",
    about_p3:"نؤمن أن كل كلب يستحق أن يشعر بالوطن — حتى عندما يكون أصحابه بعيدين.",
    about_p4:"تأسس لوفينج هومز من قبل مجموعة من عشاق الكلاب في هونغ كونغ، وأصبح أحد أكثر فنادق الكلاب ثقة في المدينة.",
    about_mission_heading:"مهمتنا",
    about_mission_text:"تقديم أفضل رعاية لكل كلب يدخل أبوابنا — التعامل معه كفرد من العائلة، لا كضيف.",
    about_vision_heading:"رؤيتنا",
    about_vision_text:"أن نكون الفندق الفاخر الأول للكلاب في هونغ كونغ، نضع المعيار الذهبي لضيافة الحيوانات الأليفة وسلامتها ورفاهيتها.",
    about_values_heading:"قيمنا",
    about_v1_title:"السلامة أولاً", about_v1_text:"كل كلب تحت مراقبة الموظفين المدربين والأطباء البيطريين على مدار الساعة.",
    about_v2_title:"الرعاية الحقيقية", about_v2_text:"نتعامل مع كل ضيف بنفس المحبة التي نمنحها لحيواناتنا الأليفة.",
    about_v3_title:"التميز", about_v3_text:"من الغرف الفاخرة إلى التزيين، نحافظ على أعلى المعايير في كل ما نقدمه.",
    about_v4_title:"الشفافية", about_v4_text:"تحديثات يومية بالصور والفيديو تبقيك على تواصل مع كلبك في كل وقت.",
    about_team_heading:"فريقنا",
    about_team_text:"يضم فريقنا أطباء بيطريين معتمدين ومزينين ذوي خبرة ومدربين متخصصين وعشاق حيوانات — جميعهم ملتزمون بجعل إقامة كلبك استثنائية.",
    about_blog_heading:"عن هذا الموقع",
    about_blog_p1:"أُنشئ هذا الموقع لمساعدة أصحاب الكلاب في هونغ كونغ على إيجاد رعاية موثوقة وعالية الجودة لحيواناتهم الأليفة.",
    about_blog_p2:"ستجد معلومات تفصيلية عن خدماتنا وباقاتنا ومرافقنا، إضافة إلى نصائح وإرشادات حول رعاية الكلاب.",
    about_blog_p3:"سواء كنت تخطط لعطلة أو تحتاج فقط إلى رعاية نهارية لكلبك، لوفينج هومز هنا لمساعدتك.",
    contact_heading:"اتصل بنا",
    contact_intro:"نحن هنا للمساعدة. إذا كان لديك أي أسئلة أو ترغب في حجز موعد، يرجى التواصل معنا:",
    location_heading:"موقعنا",
    location_text:"ستجدنا في قلب هونغ كونغ. موقعنا مريح وسهل الوصول إليه.",
    lbl_fname:"الاسم الأول:", lbl_lname:"اسم العائلة:", lbl_email:"البريد الإلكتروني:",
    lbl_message:"الرسالة:",
    btn_send:"إرسال",
    err_required:"هذا الحقل مطلوب.",
    success_msg:"✔ شكراً! تم استلام رسالتك. سنتواصل معك قريباً.",
    status_fill:"يرجى ملء جميع الحقول المطلوبة.",
    status_sending:"جارٍ الإرسال…",
    footer_text:"© 2026 فندق لوفينغ هومز للكلاب - جميع الحقوق محفوظة - هونغ كونغ، من تصميم لجين عمر الخليفات",
  },
  zh: {
    nav_home:"首頁", nav_services:"服務", nav_packages:"套餐",
    nav_gallery:"相冊", nav_about:"關於我們", nav_contact:"聯絡我們",
    home_title:"歡迎來到 Loving Homes 寵物酒店",
    home_sub1:"我們致力於為您的愛犬提供最好的照顧。",
    home_sub2:"加入我們，讓您的愛犬過上更健康、更快樂的生活！",
    video_fallback:"您的瀏覽器不支持視頻播放。",
    services_heading:"我們的服務與設施",
    services_intro:"在 Loving Homes，我們提供多種服務，確保您的愛犬擁有舒適愉快的住宿體驗。",
    s1_title:"豪華住宿客房", s1_text:"設有地熱冷暖系統、平板電視及每日更換新鮮床鋪的私人客房。",
    s2_title:"美容沙龍及水療", s2_text:"全套美容服務：沐浴、品種專屬剪毛、修剪指甲、清潔耳朵及水療護理。",
    s3_title:"安全戶外圍欄", s3_text:"寬敞且全面安全的戶外圍欄，每天供自由玩耍和呼吸新鮮空氣。",
    s4_title:"森林漫步", s4_text:"在自然林區進行風景優美的導覽漫步——非常適合運動和心理刺激。",
    s5_title:"室內遊樂場", s5_text:"一個大型室內遊樂區，適合所有天氣條件和互動群體遊戲。",
    s6_title:"禮賓車服務", s6_text:"覆蓋全香港的無壓力上門接送服務。",
    s7_title:"24/7獸醫服務", s7_text:"我們的值班獸醫團隊全天候提供服務，確保您完全放心。",
    s8_title:"寵物看護", s8_text:"對每位住客進行持續監控和每日健康檢查。",
    s9_title:"私人草地區域", s9_text:"專屬的私人草地空間，讓您的愛犬遠離群體，享受戶外放鬆與探索的時光。",
    packages_heading:"我們的套餐",
    packages_intro:"選擇最適合您愛犬需求的套餐——從單日訪問到豪華長期住宿。",
    pkg1_name:"高級套餐", pkg1_f1:"每天四次散步/活動", pkg1_f2:"私人草地區域", pkg1_f3:"每日照片和視頻更新", pkg1_f4:"按照主人協議的零食", pkg1_f5:"設有地熱冷暖系統及平板電視的豪華客房", pkg1_f6:"上門接送禮賓車服務", pkg1_f7:"24/7獸醫服務", pkg1_f8:"持續寵物監控", pkg1_f9:"美容沙龍及水療", pkg1_f10:"安全戶外圍欄",
    pkg2_name:"經典套餐", pkg2_f1:"每天三次散步/活動", pkg2_f2:"室內遊樂場", pkg2_f3:"靜心區放鬆", pkg2_f4:"美容服務", pkg2_f5:"設有地熱冷暖系統及平板電視的豪華客房", pkg2_f6:"上門接送禮賓車服務", pkg2_f7:"24/7獸醫服務", pkg2_f8:"持續寵物監控", pkg2_f9:"安全戶外圍欄",
    pkg3_name:"日間套餐", pkg3_f1:"每天兩次散步", pkg3_f2:"戶外遊樂區", pkg3_f3:"敏捷訓練跑道", pkg3_f4:"沙坑", pkg3_f5:"上門接送禮賓車服務", pkg3_f6:"24/7獸醫服務", pkg3_f7:"持續寵物監控", pkg3_f8:"安全戶外圍欄",
    pkg_custom_title:"定制套餐",
    pkg_custom_text:"為較長住宿或有特殊需求的狗狗提供定制套餐。請聯絡我們安排定制套餐。",
    gallery_heading:"相冊",
    gallery_intro:"看看我們的快樂住客在 Loving Homes 享受住宿的精彩瞬間。",
    about_heading:"關於 Loving Homes",
    about_p1:"Loving Homes 是一家位於香港的高端寵物酒店。我們致力於為您的愛寵提供安全、舒適和愉快的環境。",
    about_p2:"我們經驗豐富且充滿熱情的動物愛好者團隊提供多種服務，從豪華住宿客房和專業美容到森林漫步和24小時獸醫服務。",
    about_p3:"我們相信每隻狗都值得有家的感覺——即使牠們的主人不在身邊。",
    about_p4:"Loving Homes 由一群香港愛狗人士創立，已成為香港最受信賴的寵物酒店之一。",
    about_mission_heading:"我們的使命",
    about_mission_text:"為每一隻踏入我們大門的狗狗提供最優質的照顧——像對待家人一樣，而不僅僅是客人。",
    about_vision_heading:"我們的願景",
    about_vision_text:"成為香港頂級的高端寵物酒店，為寵物款待、安全和幸福樹立黃金標準。",
    about_values_heading:"我們的價值觀",
    about_v1_title:"安全第一", about_v1_text:"每隻狗都由受過訓練的員工和值班獸醫全天候監控。",
    about_v2_title:"真誠關懷", about_v2_text:"我們像對待自己的寵物一樣，用同樣的愛對待每位住客。",
    about_v3_title:"卓越品質", about_v3_text:"從豪華客房到美容服務，我們在每件事上都保持最高標準。",
    about_v4_title:"透明度", about_v4_text:"每日照片和視頻更新讓您隨時與愛犬保持聯繫。",
    about_team_heading:"我們的團隊",
    about_team_text:"我們的團隊包括認證獸醫、經驗豐富的美容師、訓練有素的狗狗訓練師和熱情的動物愛好者——都致力於讓您愛犬的住宿體驗非凡難忘。",
    about_blog_heading:"關於本網站",
    about_blog_p1:"本網站旨在幫助香港的狗主找到可靠、高質量的寵物護理服務。",
    about_blog_p2:"您將找到有關我們服務、套餐和設施的詳細信息，以及狗狗護理的小貼士和建議。",
    about_blog_p3:"無論您是計劃度假還是只需要為愛犬提供日間照顧，Loving Homes 都在這裡為您提供幫助。",
    contact_heading:"聯絡我們",
    contact_intro:"我們在這裡為您提供幫助。如果您有任何問題或想要預訂，請與我們聯繫：",
    location_heading:"我們的位置",
    location_text:"我們位於香港中心地帶，交通便利，易於到達。",
    lbl_fname:"名字：", lbl_lname:"姓氏：", lbl_email:"電子郵件：",
    lbl_message:"訊息：",
    btn_send:"發送",
    err_required:"此欄位為必填項。",
    success_msg:"✔ 謝謝！您的訊息已收到。我們將盡快與您聯繫。",
    status_fill:"請填寫所有必填欄位。",
    status_sending:"正在送出…",
    footer_text:"© 2026 Loving Homes 宠物酒店 - 保留所有权利 - 香港，由 Lujain Omar Khlifat 设计",
  }
};
